### ISSUE TITLE
Question about POCUS dataset

### ISSUE THREAD

**Issue by Salaare** [jannisborn/covid19_ultrasound#108]
Hello
Good time
I did some analysis on the POCUS data, but I have a question.
According to your Python code, I first converted the frames into images and then CROP them with your code.
Is it correct or should I CROP first and then convert the frames to images?

Then the next question is whether the CROP codes make the images the same size or just remove the borders?

Thankful

**Comment by jannisborn** [comment]
Hi,

Thx for the interest. It does not matter which way you do it. 
But if you run 'build_and_extract_dataset.py' all of this is taken care of, and you don't have to worry
