### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by Salaare** [jannisborn/covid19_ultrasound#109]
Excuse me.
where is the build_and_extract_dataset.py?

please guide me to achieve this code.

**Comment by jannisborn** [comment]
Follow the README here: https://github.com/jannisborn/covid19_ultrasound/tree/master/pocovidnet

Specifically, your question is covered in this section:
https://github.com/jannisborn/covid19_ultrasound/tree/master/pocovidnet#videos-to-images
