### ISSUE TITLE
Crop Images

### ISSUE THREAD

**Issue by Salaare** [jannisborn/covid19_ultrasound#110]
Your code only converted the frames into images, and I could not find the part that cropped the images.

Thank you for helping me more precisely.

**Comment by jannisborn** [comment]
Then you have to look more closely. It is covered in the first step when you run `sh get_and_process_web_data.sh`. At the bottom of the file, the cropping script is being called.

**Comment by jannisborn** [comment]
I'm closing this, feel free to re-open if applicable
