### ISSUE TITLE
missing model_factory

### ISSUE THREAD

**Issue by garytann** [jannisborn/covid19_ultrasound#113]
Hi all, I am reproducing the training environment with the train_covid19 script. However from 
```
from pocovidnet import MODEL_FACTORY
```
I cannot seemed to locate the directory to this module, anyone faced similar issues?

**Comment by jannisborn** [comment]
Hi,
Thanks for your interest. I'm pretty sure this is a local issue on your side. Are you sure that you followed the installation instructions in the README?

**Comment by garytann** [comment]
Hi @jannisborn thanks for the reply,

yes I did follow the installations via the README and I am executing the train_covid19.py script from the directory of the README of pocovidnet. However, I keep getting an error of 

```
ModuleNotFoundError: No module named 'pocovidnet2'
```
when I run the script, I have checked that the module exists in the directory

**Comment by jannisborn** [comment]
Can you

```py
cd covid19_ultrasound/pocovidnet
pip install -e .
```

and try again?

**Comment by garytann** [comment]
hi @jannisborn thanks for the help, I realised I used a different virtual env thus did not have the dependencies setup. Apologies. Please close this issue
