### ISSUE TITLE
evaluating the model

### ISSUE THREAD

**Issue by garytann** [jannisborn/covid19_ultrasound#114]
hi all, could anyone explain to me the usage of pocovidnet/scripts/test.py ? It is confusing as there is no testing dataset that is being created during the cross_validation. would appreciate some guide here

Thank you!

**Comment by jannisborn** [comment]
Purpose of the script is simply to run inference on a piece of data, see here: https://github.com/jannisborn/covid19_ultrasound/blob/master/pocovidnet/README.md#test-the-model

**Comment by garytann** [comment]
I see thanks for the information, I have tried running it with the default flags on test.py, but is encountering this issue.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datadrive/covid19_ultrasound/pocovidnet/scripts/test.py", line 240, in <module>
    main()
  File "/datadrive/covid19_ultrasound/pocovidnet/scripts/test.py", line 195, in main
    model = Evaluator(
  File "/datadrive/covid19_ultrasound/pocovidnet/pocovidnet/evaluate_covid19.py", line 101, in __init__
    raise Exception('Error in model restoring.')
Exception: Error in model restoring.
```

**Comment by jannisborn** [comment]
Read the other issues, e.g., here https://github.com/jannisborn/covid19_ultrasound/issues/103

**Comment by garytann** [comment]
hi @jannisborn thank you so much for the help
