### ISSUE TITLE
3  Videos

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_ultrasound#69]
This paper releases 3 videos:

https://www.medrxiv.org/content/10.1101/2020.10.13.20212258v2

- Vid 3 is clearly COVID
- Vid 2 is non-covid-ards: can we find whether it's bacterial or viral?
- Vid 1 is hydrostatic pulmonary edema (probably cant be sorted into any of our buckets)

**Comment by NinaWie** [comment]
I included Vid 3 in the dataset, but for the other two I think the label is too unsure. ARDS can be caused by many reasons as far as I know.

**Comment by NinaWie** [comment]
Actually, we have a folder called `label_uncertain`, so we can add videos 1 and 2 there. Reopening.
