### ISSUE TITLE
Data from esaote (company)

### ISSUE THREAD

**Issue by NinaWie** [jannisborn/covid19_ultrasound#74]
https://www.esaote.com/fr-BE/special-covid-19/our-solutions/lung-ultrasound-in-critical-care/  Several covid videos available

**Comment by NinaWie** [comment]
Probably only 2 regular images can be taken because other data is not labeled

**Comment by konstantinle** [comment]
which images are intended to be taken?

**Comment by NinaWie** [comment]
We can take everything that doesn't have (strong) artifacts and is labeled with healthy, bacterial pneumonia, covid or other viral pneumonia. On this website directly, I think we can only take the first row ("Normal lung") because the other ones either have artefacts, or they only say "consolidations" but don't say what was the underlying disease.
But maybe we can also search on the website whether they publish videos. Videos would be better than images, and it's an US company, so it's quite likely that they publish some videos to show the quality of their devices.
